[package]
name = "dex_tool"
version = "0.1.0"
authors = ["jaqxues <32979131+jaqxues@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leb128 = "0.2.5"
memmap = "0.7.0"
scroll = "0.11.0"
